Sprint 1/step 2
bobossa/react-burger pull request #1
Opened 2023-03-01 23:16 UTC by bobossa

2023-03-02 06:10 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx;
  - logo.svg;
  - App.jsx - т.к. у вас есть уже компонент App;
  - App.css;

- <https://disk.yandex.com/i/B8c22zHqatEeKw> - в конструкторе, среди ингредиентов, не должно быть булок. Вам нужно разделить булку и ингредиенты;

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- <https://disk.yandex.com/i/B8c22zHqatEeKw> - нужно убрать синюю обводку у блока, эта обводка на макете нужна только что бы сделать поясняющее описание к этому блоку;

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.
-
- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    })
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать.

**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  };
**Надо исправить:**

Тут лучше вынести в отдельный компонент, а не делать функцию. И не забудьте про `prop-types`.

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    setTargetIndegrient(targetIngredient);
**Можно лучше:**

не совсем понимаю, почему вы тут решили работать через `dataset`, можно ведь сразу в функцию прокинуть `_id`;

```js
const BurgerIngredient = (image, price, name, _id) => {
  const handleIngredientClick = () => {
    handleClick(_id)
  }

  <li onClick={handleIngredientClick}></li>
}
```

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      <div className="" style={{ display: "flex" }}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  ).isRequired,
**Надо исправить:**

Аналогичное замечание в `burger-constructor`.

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/ingredients-details/ingredient-details.jsx
> +};
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать.

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +  });
**Надо исправить:**

Вы должны указать в зависимостях `useEffect`, пустой массив, иначе у вас каждый раз при ререндере будет ставится, и убираться событие по нажатию клавиш.

2023-03-02 06:10 UTC, ArslanDev666 commented on src/components/order-details/order-details.jsx
> +      <img className="pb-15" src={done} />
**Надо исправить:**

У элемента `img` должен быть атрибут `alt`.

2023-03-02 09:30 UTC, bobossa commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      <div className="" style={{ display: "flex" }}>
✅

2023-03-02 09:30 UTC, bobossa commented on src/components/app/app.jsx
> +        const res = await fetch(GET_DATA_URL);
✅

2023-03-02 09:30 UTC, bobossa commented on src/components/app/app.jsx
> +  const [targetIndegrient, setTargetIndegrient] = React.useState({});
✅

2023-03-02 09:32 UTC, bobossa commented on src/components/modal/modal.jsx
> +  });
✅

2023-03-02 10:07 UTC, bobossa commented on src/components/order-details/order-details.jsx
> +      <img className="pb-15" src={done} />
✅

2023-03-02 10:26 UTC, bobossa commented on src/components/burger-constructor/burger-constructor.jsx
> +  const total = data.reduce((acc, cur) => acc + cur.price, 0);
✅

2023-03-02 10:27 UTC, bobossa commented on src/components/burger-constructor/burger-constructor.jsx
> +          text={`${data[0].name} (верх)`}
✅

2023-03-02 11:28 UTC, bobossa commented on src/components/burger-constructor/burger-constructor.jsx
> +    })
✅

2023-03-02 11:43 UTC, bobossa commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  ).isRequired,
✅

2023-03-02 14:54 UTC, bobossa commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    setTargetIndegrient(targetIngredient);
✅

2023-03-02 14:54 UTC, bobossa commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  };
✅

2023-03-02 20:06 UTC, bobossa commented on src/components/app/app.jsx
> +                </Modal>
✅

2023-03-02 20:07 UTC, bobossa commented on src/components/ingredients-details/ingredient-details.jsx
> +};
✅

2023-03-03 07:09 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +            {burgerIngredientArr.map((group, index) => (
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

2023-03-03 07:09 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +        setLoading(false);
**Можно лучше:**

`setLoading` лучше ставить в блоке `finally`)

2023-03-03 07:09 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const total = data.reduce((acc, cur) => acc + cur.price, 0);
Уточню, булок у нас 2 штуки именно в конструкторе (вообще у нас тоже 2 булки, но цена у них разная, а нам нужно учитывать цену именно одной из них, и умножать на 2)

2023-03-03 07:23 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть ещё несколько замечаний, которые нужно исправить:**

- Нужно исправить ошибки в консоли:
  - при открытии приложения: <https://disk.yandex.com/i/KfC4yLualQJduw>;
  - при открытии orderDetails: <https://disk.yandex.com/i/7AfEsKj1C_dZfw>;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-03-03 07:23 UTC, ArslanDev666 commented on src/components/ingredients-details/ingredient-details.jsx
> +  data: PropTypes.shape(IngredientType).isRequired,
**Можно лучше:**

Вообщем можно сразу вместе с `PropTypes.shape` вынести описание)), просто мы нигде больше не будем использовать это описание, кроме как в типах или в `prop-types`. Поэтому и выносить просто объект особого смысла нету

2023-03-03 07:23 UTC, ArslanDev666 commented on src/components/burger-inrgredient-group/burger-inrgredient-group.jsx
> +  data: PropTypes.shape(IngredientType).isRequired,
**Надо исправить:**

тут должен быть массив) 

```js
data: PropTypes.arrayOf(PropTypes.shape(IngredientType).isRequired).isRequired;
```

2023-03-03 07:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      ) : (
**Надо исправить:**

Не совсем понимаю, а зачем убирать контент, когда модалка открыта?.

2023-03-03 07:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +      ) : (
**Надо исправить:**

Не совсем понимаю, а зачем убирать контент, когда модалка открыта? Можно просто написать вот так: 
```js
{isOrderDetailsModalOpen && `модальное окно`)}
```

2023-03-03 07:23 UTC, ArslanDev666 commented on src/components/order-details/order-details.jsx
> +  data: PropTypes.shape({ IngredientType }).isRequired,
**Надо исправить:**

Кажется, вы тут ошиблись с типом) Здесь должно быть описание заказа.

```js
data: PropTypes.shape({ orderNumber:  PropTypes.string.isRequired }).isRequired,
```

2023-03-03 07:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +          <OrderDetails onClose={setOrderDetailsModalOpen} data={ORDER_DATA} />
**Надо исправить:**

`onClose` пропс тут лишний, вы его не используете

2023-03-03 07:40 UTC, bobossa commented on src/components/burger-inrgredient-group/burger-inrgredient-group.jsx
> +  data: PropTypes.shape(IngredientType).isRequired,
✅

2023-03-03 07:43 UTC, bobossa commented on src/components/burger-constructor/burger-constructor.jsx
> +      ) : (
✅

2023-03-03 07:47 UTC, bobossa commented on src/components/order-details/order-details.jsx
> +  data: PropTypes.shape({ IngredientType }).isRequired,
✅

2023-03-03 07:47 UTC, bobossa commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      ) : (
✅

2023-03-03 07:53 UTC, bobossa commented on src/components/burger-inrgredient-group/burger-inrgredient-group.jsx
> +  data: PropTypes.shape(IngredientType).isRequired,
✅

2023-03-03 07:54 UTC, bobossa commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      ) : (
✅

2023-03-03 07:56 UTC, bobossa commented on src/components/burger-constructor/burger-constructor.jsx
> +          <OrderDetails onClose={setOrderDetailsModalOpen} data={ORDER_DATA} />
✅

2023-03-03 07:57 UTC, bobossa commented on src/components/app/app.jsx
> +        setLoading(false);
✅

2023-03-03 11:18 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа! 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-03-03 17:40 UTC, merged