sprint-2/step-2
bobossa/react-burger pull request #2
Opened 2023-03-11 08:39 UTC by bobossa

2023-03-11 09:25 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
- Использовали `useMemo` и `useCallback`
- Созданы все необходимые экшены для запросов
- Хорошо организовано хранилище

Что необходимо исправить:
- Если в конструкторе пусто, то кнопку заказа стоит дизейблить или скрывать, иначе при оформлении пустого заказа появляется ошибка и ломается логика работы приложения.
<img width="1440" alt="Снимок экрана 2023-03-11 в 12 15 57" src="https://user-images.githubusercontent.com/60173362/224475979-de8c6c52-bd39-4e06-9f06-35b1ab474490.png">

- не нужно хранить отдельно в сторе массив ингредиентов для отправки, создавайте массив при отправке из данных конструктора. Вообще любое дублирование информации с сторе считается плохой практикой
- Рассортируйте редьюсеры на несколько файлов по модулям, к которым они относятся.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-11 09:25 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const orderDetails = useSelector((store) => store.orderDetails);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-11 09:25 UTC, andryxxa93 commented on src/components/order-details/order-details.jsx
> +  console.log(data);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией

2023-03-11 09:25 UTC, andryxxa93 commented on src/services/reducers/reducers.jsx
> +import {
**Надо исправить**
следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

В текущем приложении можно разделить на следующие файлы:
- загрузка данных ингредиентов
- работа конструктора
- открытие ингредиента в попапе
- оформление заказа

2023-03-11 13:41 UTC, bobossa commented on src/components/order-details/order-details.jsx
> +  console.log(data);
✅

2023-03-11 13:41 UTC, bobossa commented on src/components/order-details/order-details.jsx
> +  console.log(data);
✅

2023-03-11 13:41 UTC, bobossa commented on src/services/reducers/reducers.jsx
> +import {
✅

2023-03-12 05:26 UTC, andryxxa93 requested changes
Отлично! Но теперь почему-то номер заказа не показывается, хотя в сторе он уже появился. Исправьте это и работа будет принята - 
<img width="1438" alt="Снимок экрана 2023-03-12 в 08 25 29" src="https://user-images.githubusercontent.com/60173362/224526134-fb156193-51af-48e3-a825-fe4c610877cd.png">

2023-03-13 05:32 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-13 17:35 UTC, merged